Repository codesquad-masters2024-airdnb-team12/be-airdnb, pull requests merged in 2024-06, with the labels that each got.

#2 Feat/#1 Entity class 생성
  src/main/java/com/airbnb/domain/accommodation/Accommodation.java
  src/main/java/com/airbnb/domain/accommodationDiscount/AccommodationDiscount.java
  src/main/java/com/airbnb/domain/accommodationHashtag/AccommodationHashtag.java
  src/main/java/com/airbnb/domain/accommodationHashtag/AccommodationHashtagId.java
  src/main/java/com/airbnb/domain/accommodationImg/AccommodationImg.java
  src/main/java/com/airbnb/domain/booking/Booking.java
  src/main/java/com/airbnb/domain/common/Address.java
  src/main/java/com/airbnb/domain/common/BaseTime.java
  src/main/java/com/airbnb/domain/common/LoginType.java
  src/main/java/com/airbnb/domain/common/Role.java
  src/main/java/com/airbnb/domain/hashtag/Hashtag.java
  src/main/java/com/airbnb/domain/hashtag/HashtagType.java
  src/main/java/com/airbnb/domain/like/Like.java
  src/main/java/com/airbnb/domain/like/LikeId.java
  src/main/java/com/airbnb/domain/member/Member.java
  src/main/java/com/airbnb/domain/payment/Card.java
  src/main/java/com/airbnb/domain/payment/Payment.java
  src/main/java/com/airbnb/domain/payment/PaymentStatus.java
  src/main/java/com/airbnb/domain/policy/DiscountPolicy.java
  src/main/java/com/airbnb/domain/policy/FeePolicy.java
  src/main/java/com/airbnb/domain/review/Review.java
  src/main/resources/application.yml
Labels: feature ✨, 담당: sylve 🤍, 담당: sharpie 🌟

#8 Feat/#4 숙소 등록 기능 구현
  build.gradle
  src/main/java/com/airbnb/domain/AccommodationInfo/entity/AccommodationInfo.java
  src/main/java/com/airbnb/domain/accommodation/controller/AccommodationController.java
  src/main/java/com/airbnb/domain/accommodation/dto/request/AccommodationCreateRequest.java
  src/main/java/com/airbnb/domain/accommodation/dto/request/AccommodationInfoRequest.java
  src/main/java/com/airbnb/domain/accommodation/dto/response/AccommodationResponse.java
  src/main/java/com/airbnb/domain/accommodation/entity/Accommodation.java
  src/main/java/com/airbnb/domain/accommodation/entity/AccommodationType.java
  src/main/java/com/airbnb/domain/accommodation/entity/BuildingType.java
  src/main/java/com/airbnb/domain/accommodation/repository/AccommodationRepository.java
  src/main/java/com/airbnb/domain/accommodation/service/AccommodationService.java
  src/main/java/com/airbnb/domain/accommodationDiscount/AccommodationDiscount.java
  src/main/java/com/airbnb/domain/accommodationFacility/AccommodationFacility.java
  src/main/java/com/airbnb/domain/accommodationFacility/AccommodationFacilityId.java
  src/main/java/com/airbnb/domain/accommodationHashtag/AccommodationHashtag.java
  src/main/java/com/airbnb/domain/accommodationImg/AccommodationImg.java
  src/main/java/com/airbnb/domain/booking/Booking.java
  src/main/java/com/airbnb/domain/common/Address.java
  src/main/java/com/airbnb/domain/common/FacilityType.java
  src/main/java/com/airbnb/domain/facility/entity/Facility.java
  src/main/java/com/airbnb/domain/facility/repository/FacilityRepository.java
  src/main/java/com/airbnb/domain/hashtag/HashtagType.java
  src/main/java/com/airbnb/domain/like/Like.java
  src/main/java/com/airbnb/domain/member/repository/MemberRepository.java
  src/main/java/com/airbnb/domain/review/Review.java
  src/main/java/com/airbnb/global/validator/NoNullElements.java
  src/main/java/com/airbnb/global/validator/NoNullElementsValidator.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/airbnb/accommodation/unit/controller/AccommodationControllerTest.java
  src/test/java/com/airbnb/accommodation/unit/service/AccommodationServiceTest.java
Labels: feature ✨, 담당: sharpie 🌟

#10 [Feat/#7] TourApi 숙박업소 데이터 DB에 넣는 파이썬 코드 추가
  AccommodationDBInsert/data.md
  AccommodationDBInsert/dbInsert.py
Labels: feature ✨, 담당: sharpie 🌟

#11 [Feat/#6] OAuth 로그인 기능 구현
  build.gradle
  src/main/java/com/airbnb/config/RestTemplateConfig.java
  src/main/java/com/airbnb/config/SecurityConfig.java
  src/main/java/com/airbnb/domain/common/Role.java
  src/main/java/com/airbnb/domain/member/controller/MemberController.java
  src/main/java/com/airbnb/domain/member/dto/request/SignUpRequest.java
  src/main/java/com/airbnb/domain/member/dto/request/UpdateMemberRequest.java
  src/main/java/com/airbnb/domain/member/dto/response/LogInResponse.java
  src/main/java/com/airbnb/domain/member/dto/response/MemberListResponse.java
  src/main/java/com/airbnb/domain/member/dto/response/MemberResponse.java
  src/main/java/com/airbnb/domain/member/entity/Member.java
  src/main/java/com/airbnb/domain/member/entity/bankAccount/BankType.java
  src/main/java/com/airbnb/domain/member/service/MemberService.java
  src/main/java/com/airbnb/global/auth/jwt/JwtAuthFilter.java
  src/main/java/com/airbnb/global/auth/jwt/JwtUtil.java
  src/main/java/com/airbnb/global/auth/oauth2/exception/OAuth2ProcessingException.java
  src/main/java/com/airbnb/global/auth/oauth2/handler/OAuth2SuccessHandler.java
  src/main/java/com/airbnb/global/auth/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/airbnb/global/auth/oauth2/user/OAuth2UserInfo.java
  src/main/java/com/airbnb/global/auth/oauth2/user/OAuth2UserPrincipal.java
  src/main/java/com/airbnb/global/security/PasswordEncoder.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
Labels: feature ✨, 담당: sylve 🤍

#17 [Fix/#13] 숙소 페이지 조회 시 숙소 전체개수 조회 오류 해결 및 응답 형태 변경
  src/main/java/com/airbnb/domain/accommodation/dto/response/AccommodationDetailResponse.java
  src/main/java/com/airbnb/domain/accommodation/dto/response/AccommodationPageResponse.java
  src/main/java/com/airbnb/domain/booking/service/BookingService.java
  src/main/java/com/airbnb/domain/payment/Payment.java
  src/main/java/com/airbnb/domain/policy/repository/DiscountPolicyRepository.java
  src/main/java/com/airbnb/domain/policy/repository/FeePolicyRepository.java
  src/main/java/com/airbnb/domain/policy/service/PolicyService.java
  src/main/java/com/airbnb/global/config/SecurityConfig.java
  src/main/resources/application.yml
  src/test/java/com/airbnb/accommodation/unit/controller/AccommodationControllerTest.java
  src/test/java/com/airbnb/accommodation/unit/service/AccommodationServiceTest.java
Labels: fix 🩹, 담당: sharpie 🌟
